CODE/logistic_and_supply_chain/logistic_and_supply_chain/urls.py
from django.contrib import admin
from admins import views as admins
from django.urls import path
from users import views as usr
from . import views as mainView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainView.index, name='index'),
    path("UserRegister/", mainView.UserRegister, name="UserRegister"),
    path("AdminLogin/", mainView.AdminLogin, name="AdminLogin"),
    path('index/', mainView.index, name='index'),
    path("UserLogin/", mainView.UserLogin, name="UserLogin"),
    path("Viewdata/", mainView.Viewdata, name="Viewdata"),

    # User Side Views
    path("UserRegisterActions/", usr.UserRegisterActions,
         name="UserRegisterActions"),
    path("UserLoginCheck/", usr.UserLoginCheck, name="UserLoginCheck"),
    path("UserHome/", usr.UserHome, name="UserHome"),
    path("viewdata/", usr.viewdata, name="viewdata"),

    # Admin Side Views
    path("AdminLoginCheck/", admins.AdminLoginCheck, name="AdminLoginCheck"),
    path("AdminHome/", admins.AdminHome, name="AdminHome"),
    path("ViewRegisteredUsers/", admins.ViewRegisteredUsers,
         name="ViewRegisteredUsers"),
    path("AdminActivaUsers/", admins.AdminActivaUsers, name="AdminActivaUsers"),
    # path("AdminDataPreProcess/", admins.AdminDataPreProcess, name="AdminDataPreProcess"),
    path("Arma", usr.Arma, name="Arma"),

]

logistic_and_supply_chain/urls.py
from django.contrib import admin
from admins import views as admins
from django.urls import path
from users import views as usr
from . import views as mainView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainView.index, name='index'),
    path("UserRegister/", mainView.UserRegister, name="UserRegister"),
    path("AdminLogin/", mainView.AdminLogin, name="AdminLogin"),
    path('index/', mainView.index, name='index'),
    path("UserLogin/", mainView.UserLogin, name="UserLogin"),
    path("Viewdata/", mainView.Viewdata, name="Viewdata"),

    # User Side Views
    path("UserRegisterActions/", usr.UserRegisterActions,
         name="UserRegisterActions"),
    path("UserLoginCheck/", usr.UserLoginCheck, name="UserLoginCheck"),
    path("UserHome/", usr.UserHome, name="UserHome"),
    path("viewdata/", usr.viewdata, name="viewdata"),

    # Admin Side Views
    path("AdminLoginCheck/", admins.AdminLoginCheck, name="AdminLoginCheck"),
    path("AdminHome/", admins.AdminHome, name="AdminHome"),
    path("ViewRegisteredUsers/", admins.ViewRegisteredUsers,
         name="ViewRegisteredUsers"),
    path("AdminActivaUsers/", admins.AdminActivaUsers, name="AdminActivaUsers"),
    # path("AdminDataPreProcess/", admins.AdminDataPreProcess, name="AdminDataPreProcess"),
    path("Arma", usr.Arma, name="Arma"),

]

users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                           required=True, max_length=100)

    loginid = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                              required=True, max_length=100)

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}', 'class': 'form-control',
                                          'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters'}),
        required=True, max_length=100)

    mobile = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[56789][0-9]{9}', 'class': 'form-control'}),
                             required=True,
                             max_length=100)

    email = forms.CharField(
        widget=forms.TextInput(attrs={'pattern': '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$', 'class': 'form-control'}),
        required=True, max_length=100)

    locality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, max_length=100)

    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 20, 'class': 'form-control'}),
                              required=True, max_length=250)

    city = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    state = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    status = forms.CharField(widget=forms.HiddenInput(), initial='waiting', max_length=100)

    class Meta():
        model = UserRegistrationModel
        fields = '__all__'

CODE/logistic_and_supply_chain/assets/templates/AdminLogin.html
{% extends  'base.html' %}
{% load static %}

{% block title %}
    Admin Login
{% endblock %}
{% block admin_login %}
    active
{% endblock %}


{% block content %}
    <style>

        body {
            background: #fff;

        }

        .jumbotron {
            font-family: "Book Antiqua";
            margin-top: 9%;
            background: #fff;
        }

        .card-body {
            width: 50%;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        }


    </style>

    <center>
        <div class="jumbotron">
            <div class="container">


                <div class="card card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <form action="{% url 'AdminLoginCheck' %}" method="POST" class="text-primary">
                                {% csrf_token %}
                                <legend style="float: right"> Admin</legend>
                                <br><br>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" name="loginid" required
                                               placeholder="Enter Login Id">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="password" class="form-control" name="pswd" required
                                               placeholder="Enter password">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">

                                        <center>
                                            <input type="submit" class="btn btn-block btn-primary"
                                                   value="Sign in">
                                            &nbsp;
                                            <input type="reset" class="btn btn-block btn-dark">
                                        </center>
                                    </div>
                                </div>


                                <!-- Message -->
                                {% if messages %}
                                    {% for message in messages %}
                                        <p align="center" class="text-primary"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}


                            </form>

                        </div>
                    </div>
                </div>

            </div>

        </div>
    </center>



{% endblock %}

CODE/logistic_and_supply_chain/assets/templates/UserLogin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Login{% endblock %}
{% block user_login %}active{% endblock %}

{% block content %}


    <style>
        body {
            background: #fff;
        }

        .jumbotron {
            font-family: "Book Antiqua";
            margin-top: 9%;
            background: #fff;

        }

        .card-body {
            width: 50%;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);

        }

    </style>
    <center>
        <div class="jumbotron">
            <div class="container">
                <div class="card card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <form action="{% url 'UserLoginCheck' %}" method="POST" class="text-primary">
                                {% csrf_token %}

                                <legend style="float: right"> User</legend>

                                <br> <br>
                                <br>

                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" name="loginname" required
                                               placeholder="Enter Login Id">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="password" class="form-control" name="pswd" required
                                               placeholder="Enter password">
                                    </div>
                                </div>
                                <br>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="submit" class="btn btn-block btn-primary text-white" value="Sign in"> &nbsp;
                                        <input type="reset" class="btn btn-block btn-dark">

                                    </div>
                                </div>


                                <!-- Message -->
                                {% if messages %}
                                    {% for message in messages %}
                                        <p align="center" class="text-primary"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </center>
{% endblock %}

CODE/logistic_and_supply_chain/assets/templates/UserRegistrations.html
{% extends 'base.html' %}
{% block register %}

{% endblock %}

<style>


    .jumbotron {
        font-family: "Book Antiqua";
        margin-top: 100px;
    }

    .card {

        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        transition: 0.3s;
    }

    .width {
        width: 90%;
    }

</style>

{% block content %}

    <main id="main">

        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="jumbotron">
                <div class="container" style="color: white">

                    <center>
                        <div class="row" data-aos="fade-in">

                            <!--form -->

                            <div class="container width" id="register">
                                <div class="row card  card-body" style="background: #00192d;">
                                    <form action="{% url 'UserRegisterActions' %}" method="POST">


                                        <div class="section-title">
                                            <legend class="text-primary">User Sign Up</legend>
                                            <br>
                                        </div>
                                        {% csrf_token %}

                                        <div class="form-row">
                                            <div class="form-group col-md-4">
                                                <label for="id_name">User Name</label>
                                                {{ form.name }}
                                            </div>

                                            <div class="form-group col-md-4">
                                                <label for="id_loginid">Login Id</label>
                                                {{ form.loginid }}
                                            </div>


                                            <div class="form-group col-md-4">
                                                <label for="id_email">Email</label>
                                                {{ form.email }}
                                            </div>

                                            <div class="form-group col-md-4">
                                                <label for="id_mobile">Mobile</label>
                                                {{ form.mobile }}
                                            </div>


                                            <div class="form-group col-md-4">
                                                <label for="id_password">Password</label>
                                                {{ form.password }}
                                            </div>


                                            <div class="form-group col-md-4">
                                                <label for="id_locality">Locality</label>
                                                {{ form.locality }}
                                            </div>

                                        </div>

                                        <div class="form-row">
                                            <div class="form-group col-md-4">
                                                <label for="id_city">City</label>
                                                {{ form.city }}
                                            </div>

                                            <div class="form-group col-md-4">

                                            </div>
                                            <div class="form-group col-md-4">
                                                <label for="id_state">State</label>
                                                {{ form.state }}
                                            </div>
                                            <div class="form-group col-md-2">
                                                {#                            <label for="id_status">Status</label>#}
                                                {{ form.status }}
                                            </div>


                                            <div class="form-group col-md-8">
                                                <label for="id_address">Address </label>
                                                {{ form.address }}

                                            </div>


                                        </div>


                                        <button type="submit" class="btn btn-primary m-2">Sign up</button>
                                        <button type="reset" class="btn btn-dark m-2">Reset</button>
                                        <!-- Message -->
                                        {% if messages %}
                                            {% for message in messages %}
                                                <p align="center" class="text-primary"> {{ message }}</p>
                                            {% endfor %}
                                        {% endif %}

                                    </form>
                                </div>
                            </div>
                        </div>
                    </center>
                </div>
            </div>
        </section><!-- End Contact Section -->

    </main><!-- End #main -->

{% endblock %}

CODE/logistic_and_supply_chain/assets/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Logistics & supply chain</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Main css-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


    <style>

        .btn-primary {

            border: 2px solid #fff;
            color: #fff;
            background: #00192d;
        }

        .btn-primary:hover {
            background: #00192d;
            border: 2px solid #00192d;
        }
        .bg-dark{
            background: #00192d !important;
        }
    </style>


</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top bg-dark ">
    <div class="container d-flex align-items-center justify-content-between">

        <h1 class="logo"><a href="{% url 'index' %}" style="color: #47a7d7;">Logistics<span
                class="text-white"></span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto" href="{% url 'index' %}">Home</a></li>
                <li><a class="nav-link scrollto {% block user_login %}{% endblock %}"
                       href="{% url 'UserLogin' %}">User</a></li>
                <li>
                    <a class="nav-link scrollto {% block admin_login %} {% endblock %}" href="{% url 'AdminLogin' %}">
                        Admin
                    </a>
                </li>


                <li>
                    <a class="btn btn-primary p-2 scrollto {% block register %} {% endblock %}"
                       href="{% url 'UserRegister' %}">
                        Register
                    </a>
                </li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->


{% block content %}

{% endblock %}
<!-- ======= Footer ======= -->
<footer id="footer" class="text-white" style="background: #00192d;">
    <br>
    <div class="text-center">
        <div class="copyright">
            &copy; Copyright <strong style="color: #47a7d7;">Logistics<span class="text-white"></span></strong>.
            All Rights
            Reserved
        </div>
        <div class="credits text-white">
            Designed by <a href="" class="text-info">Alex Corporation</a>
        </div>
    </div>
    <br><br>

</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

CODE/logistic_and_supply_chain/assets/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Logistics & Supply Chain</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <style>

        .btn-primary {

            border: 2px solid #fff;
            color: #fff;
            background: #00192d;
        }



        .btn-primary:hover {
            background: #00192d;
            border: 2px solid #00192d;
        }



    </style>


</head>


<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top "  style="background: #00192d;">
    <div class="container d-flex align-items-center justify-content-between">

        <h1 class="logo"><a href="{% url 'index' %}" class="">Logistics </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto active" href="{% url 'index' %}">Home</a></li>
                <li><a class="nav-link scrollto" href="{% url 'UserLogin' %}">User</a></li>
                <li><a class="nav-link scrollto" href="{% url 'AdminLogin' %}">Admin</a></li>


                <li><a class="btn btn-primary p-2 scrollto" href="{% url 'UserRegister' %}">Register</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero">
    <div class="hero-container">
        {#        <h3>Predict Your<strong>Customer</strong></h3>#}
        <h1 class="display-">Logistics & Supply Chain </h1>
        <h5 class="text-white">Role of Artificial Intelligence in Logistics and Supply Chain </h5><br>
        <a href="{% url 'UserRegister' %}" class="btn-get-started scrollto">Get Started</a>
    </div>
</section><!-- End Hero -->


<!-- ======= Footer ======= -->
<footer id="footer" class="text-white" style="background: #00192d;">
    <br>
    <div class="text-center">
        <div class="copyright">
            &copy; Copyright <strong style="color: #47a7d7;">Logistics<span class="text-white"> </span></strong>.
            All Rights
            Reserved
        </div>
        <div class="credits text-white">
            Designed by <a href="" class="text-info">Alex Corporation</a>
        </div>
    </div>
    <br><br>

</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>